# Site settings
title: Matthias Treber
email: mtreber18@mailbox.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://materpillar.github.io" # the base hostname & protocol for your site
github_username:  materpillar
linkedin_username: matthiastreber

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
